### PR TITLE
Maintenance work

### PR DESCRIPTION
**Pull request by marekkalnik**
Added autoload.php to gitignore (to allow easy test versionning) and composer.json.

### CODE REVIEW

**Comment by marekkalnik** [comment]
I'm not sure as for the authors in composer.json. Will Theodo be enough or we add everyone who actually worked on the project? If so - what about people that have made pull requests?

**Comment by benja-M-1** [comment]
You can do as they do in FOSUserBundle: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/composer.json#L8

**Comment by benja-M-1** [comment]
You must add `"doctrine/doctrine-fixtures-bundle": "dev-master"` as the bundle provides DataFixtures.
And doctrine as well I think.

```
        "doctrine/orm": "2.2.0",
        "doctrine/doctrine-bundle": "dev-master",
```

**Comment by benja-M-1** [comment]
The composer.json does not work. Here is what I changed to fix it. But I didn't test the installation in a project...

```
"require": {
  "php":">=5.3.2",
  "symfony/symfony":"2.1.*",
  "doctrine/doctrine-fixtures-bundle": "dev-master",
  "stof/doctrine-extensions-bundle":"dev-master",
  "twig/twig":">=1.2.0"
},
```

**Comment by marekkalnik** [comment]
Strange, I've tested it yesterday, seemed to work for me. I'm fixing it.

**Comment by marekkalnik** [comment]
Ok, I've retested and fixed what was necessary.

**Comment by benja-M-1** [comment]
I think we can merge this PR.

**Pull request merged**
