### PR TITLE
Fixed fixtures

### PR DESCRIPTION
**Pull request by michalpipa**
Fixes fixtures loading. It was broken because doctrine-fixtures was changed.

### CODE REVIEW

**Comment by benja-M-1** [comment]
It breaks the tests on the sf2.0.x branch, I think the deps file of the fixtures needs to be updated.

**Comment by michalpipa** [comment]
Tests are broken even without my commit. Error message says that 'Symfony\Component\DependencyInjection\ContainerAware' is missing. I haven't touch this.

**Comment by michalpipa** [comment]
OK, ignore my previous comment, it was my mistake.

I've updated vendors and now tests are passing.

**Comment by benja-M-1** [comment]
Thank you for contributing :)

**Pull request merged**
