### PR TITLE
Security

### PR DESCRIPTION
**Pull request by benja-M-1**
Add security in the controllers and in templates.

### CODE REVIEW

**Comment by benja-M-1** [comment]
build status : http://travis-ci.org/#!/benja-M-1/TheodoRogerCmsBundle

I'm working on a "Save and publish" button, I'll add it to this PR.

**Comment by marekkalnik** [comment]
Could you rebase on master?

**Comment by benja-M-1** [comment]
I "rebased" ...

**Comment by marekkalnik** [comment]
I rebased your commits on top of master and merged it from my repository.

**Pull request closed without merging**
